version: '3.9'

volumes:
  pg_data:

services:

  db:
    image: postgres:16
    env_file: db.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./src/
    command: >
      sh -c "alembic upgrade head && python main.py"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started